project:
  type: website

website:
  title: "Yahanan Anassé"
  navbar:
    left: 
      - text: Accueil
        file: index.qmd
      - text: Mes travaux
        file: travaux.qmd
      - text: Voir/ Télécharger mon CV
        file: cv.qmd
    right:
      - icon: github
        href: https://github.com/yahn78
      - icon: gmail
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

